apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: dhruvpatel33343/microservice_order_service:latest
        ports:
        - containerPort: 5003
        env:
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: "user"
        - name: DATABASE_PASSWORD
          value: "password"
        - name: DATABASE_NAME
          value: "order_db"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:5002/products"
        - name: USER_SERVICE_URL
          value: "http://user-service:5001/users"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
