apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: dhruvpatel33343/microservice_user_service:latest
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: "user"
        - name: DATABASE_PASSWORD
          value: "password"
        - name: DATABASE_NAME
          value: "user_db"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:5002/products"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:5003/orders"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
