apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app: {{ include "postgres.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "postgres.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgresUser }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresPassword }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresDatabase }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
        - name: init-script
          configMap:
            name: postgres-init-script
